# This a workflow to ensure all written project code passes pylint and pytest
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "**/*.py"
  workflow_dispatch:
jobs:
  quality_control:
    name: "Quality Control"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the Code"
        uses: actions/checkout@v4
      - name: "Install Python"
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: "Install all libraries"
        run: |
          pip install pytest pylint
          for FILE in $(find . -name 'requirements.txt'); do
            pip install -r $FILE
          done
          echo "library installation complete"
      - name: "Run Pytest"
        run: |
            pytest "**/*.py"
            echo "Ran pytest"
      - name: "Run Pylint"
        run: |
            pylint --fail-under=8 $(find . -name "*.py")
            echo "Ran pylint checks"
        
